version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db
    restart: always
  mongo-init:
    image: mongo:6.0
    depends_on:
      - mongodb
    entrypoint: >
      bash -c "
        echo 'Waiting for MongoDB to be ready...' &&
        sleep 5 &&
        mongosh --host mongodb --eval '
          try {
            rs.initiate({
              _id: \"rs0\",
              members: [{ _id: 0, host: \"mongodb:27017\" }]
            });
          } catch(e) { print(e); }
          sleep(1000);
          db.getSiblingDB(\"admin\").createUser({
            user: \"mongoadmin\",
            pwd: \"secret\",
            roles: [{ role: \"root\", db: \"admin\" }]
          });
        '
      "
    restart: "no"
  backend:
    build:
      args:
        - REACT_APP_API_HOST=http://localhost/api
      context: ./
    image: datafusion.azurecr.io/datafusionai:latest
    ports:
      - "80:80"
    environment:
      - PORT=80
      - CORS=http://localhost
      - DB_USERNAME=datafusion-ai-server
      - DB_PASSWORD=1TMasUjfJY4TLhfR02qYAyrkoqjJzqawdrftNcP4XZaCsnVcKnmEFldCjw9eO7IViYMmJPPtqNQCACDbVV3YEw==
      - DB_URI=mongodb://datafusion-ai-server:1TMasUjfJY4TLhfR02qYAyrkoqjJzqawdrftNcP4XZaCsnVcKnmEFldCjw9eO7IViYMmJPPtqNQCACDbVV3YEw==@datafusion-ai-server.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@datafusion-ai-server@
      - AZURE_GPT4_API_KEY=2PrSbQHtocJyOLuhGdUupM1IOaQbPVpdLoxkNAyHhaZGxFiPxKahJQQJ99BCACL93NaXJ3w3AAABACOGxAcf
      - AZURE_GPT4_ENDPOINT=https://datafusion-azureopenai.openai.azure.com/openai/deployments/gpt-4/chat/completions?api-version=2025-01-01-preview
      - mongo-init
    restart: always
volumes:
  mongo-data:
